// AUTO-GENERATED FILE. DO NOT EDIT.
// Source: colors.json
// Entries: 1013
package com.primortex.color.service

import com.primortex.color.app.PickedColor

object ColorNameIndex {
    data class Result(val name: String, val argb: Int)

    private fun norm(s: String): String =
        s.trim().lowercase().split(Regex("\\s+")).joinToString(" ")

    // Sorted by normalized name
    private val NAMES_NORM: Array<String> = arrayOf(
        "absolute zero",
        "acid",
        "aero",
        "air superiority blue",
        "alabaster",
        "alice blue",
        "alloy orange",
        "almond",
        "amber",
        "amethyst",
        "anti-flash white",
        "antique brass",
        "antique bronze",
        "antique fuchsia",
        "antique ruby",
        "antique white",
        "ao (english)",
        "apple green",
        "apricot",
        "aqua",
        "aquamarine",
        "arctic lime",
        "army green",
        "artichoke",
        "arylide yellow",
        "ash gray",
        "asparagus",
        "atomic tangerine",
        "auburn",
        "aureolin",
        "avocado",
        "azure",
        "b'dazzled blue",
        "baby blue",
        "baby blue eyes",
        "baby pink",
        "baker-miller pink",
        "banana mania",
        "barbie pink",
        "barbie pink (pantone)",
        "barn red",
        "battleship grey",
        "beau blue",
        "beaver",
        "beige",
        "big dip o&rsquo;ruby",
        "bisque",
        "bistre",
        "bistre brown",
        "bitter lemon",
        "bitter lime",
        "bittersweet",
        "bittersweet shimmer",
        "black",
        "black bean",
        "black chocolate",
        "black coffee",
        "black coral",
        "black olive",
        "black shadows",
        "blanched almond",
        "blast-off bronze",
        "bleu de france",
        "blizzard blue",
        "blond",
        "blood red",
        "blue",
        "blue (crayola)",
        "blue (munsell)",
        "blue (ncs)",
        "blue (pantone)",
        "blue (pigment)",
        "blue (ryb)",
        "blue bell",
        "blue jeans",
        "blue sapphire",
        "blue yonder",
        "blue-gray",
        "blue-green",
        "blue-green (color wheel)",
        "blue-violet",
        "blue-violet (color wheel)",
        "blue-violet (crayola)",
        "bluetiful",
        "blush",
        "bole",
        "bondi blue",
        "bone",
        "bottle green",
        "brandy",
        "brick red",
        "bright green",
        "bright lilac",
        "bright maroon",
        "bright navy blue",
        "bright pink",
        "bright yellow (crayola)",
        "brilliant rose",
        "brink pink",
        "british racing green",
        "bronze",
        "brown",
        "brown sugar",
        "brunswick green",
        "bubbles",
        "bud green",
        "buff",
        "burgundy",
        "burlywood",
        "burnished brown",
        "burnt orange",
        "burnt sienna",
        "burnt umber",
        "byzantine",
        "byzantium",
        "cadet",
        "cadet blue",
        "cadet blue (crayola)",
        "cadet grey",
        "cadmium green",
        "cadmium orange",
        "cadmium red",
        "cadmium yellow",
        "caf&eacute; au lait",
        "caf&eacute; noir",
        "cal poly pomona green",
        "cambridge blue",
        "camel",
        "cameo pink",
        "canary",
        "canary yellow",
        "candy apple red",
        "candy pink",
        "capri",
        "caput mortuum",
        "cardinal",
        "caribbean green",
        "carmine",
        "carmine (m&amp;p)",
        "carnation pink",
        "carnelian",
        "carolina blue",
        "carrot orange",
        "castleton green",
        "catawba",
        "cedar chest",
        "celadon",
        "celadon blue",
        "celadon green",
        "celeste",
        "celtic blue",
        "cerise",
        "cerulean",
        "cerulean (crayola)",
        "cerulean blue",
        "cerulean frost",
        "cg blue",
        "cg red",
        "champagne",
        "champagne pink",
        "charcoal",
        "charleston green",
        "charm pink",
        "chartreuse (traditional)",
        "chartreuse (web)",
        "cherry blossom pink",
        "chestnut",
        "china pink",
        "china rose",
        "chinese red",
        "chinese violet",
        "chinese yellow",
        "chocolate (traditional)",
        "chocolate (web)",
        "chrome yellow",
        "cinereous",
        "cinnabar",
        "cinnamon satin",
        "citrine",
        "citron",
        "claret",
        "cobalt blue",
        "cocoa brown",
        "coffee",
        "columbia blue",
        "congo pink",
        "cool grey",
        "copper",
        "copper (crayola)",
        "copper penny",
        "copper red",
        "copper rose",
        "coquelicot",
        "coral",
        "coral pink",
        "cordovan",
        "corn",
        "cornflower blue",
        "cornsilk",
        "cosmic cobalt",
        "cosmic latte",
        "cosmos pink",
        "cotton candy",
        "coyote brown",
        "cream",
        "crimson",
        "cultured",
        "cyan",
        "cyan (process)",
        "cyber grape",
        "cyber yellow",
        "cyclamen",
        "dark blue-gray",
        "dark brown",
        "dark byzantium",
        "dark cornflower blue",
        "dark cyan",
        "dark electric blue",
        "dark goldenrod",
        "dark green",
        "dark green (x11)",
        "dark jungle green",
        "dark khaki",
        "dark lava",
        "dark liver",
        "dark liver (horses)",
        "dark magenta",
        "dark medium gray",
        "dark moss green",
        "dark olive green",
        "dark orange",
        "dark orchid",
        "dark pastel green",
        "dark purple",
        "dark red",
        "dark salmon",
        "dark sea green",
        "dark sienna",
        "dark sky blue",
        "dark slate blue",
        "dark slate gray",
        "dark spring green",
        "dark turquoise",
        "dark violet",
        "dartmouth green",
        "davy's grey",
        "deep cerise",
        "deep champagne",
        "deep chestnut",
        "deep fuchsia",
        "deep jungle green",
        "deep pink",
        "deep saffron",
        "deep sky blue",
        "deep space sparkle",
        "deep taupe",
        "denim",
        "denim blue",
        "desert",
        "desert sand",
        "dim gray",
        "dodger blue",
        "dogwood rose",
        "drab",
        "duke blue",
        "dutch white",
        "earth yellow",
        "ebony",
        "ecru",
        "eerie black",
        "eggplant",
        "eggshell",
        "egyptian blue",
        "electric blue",
        "electric green",
        "electric indigo",
        "electric lime",
        "electric purple",
        "electric violet",
        "emerald",
        "eminence",
        "english green",
        "english lavender",
        "english red",
        "english vermillion",
        "english violet",
        "erin",
        "eton blue",
        "fallow",
        "falu red",
        "fandango",
        "fandango pink",
        "fashion fuchsia",
        "fawn",
        "feldgrau",
        "fern green",
        "field drab",
        "fiery rose",
        "fire engine red",
        "fire opal",
        "firebrick",
        "flame",
        "flavescent",
        "flax",
        "flesh",
        "flirt",
        "floral white",
        "fluorescent blue",
        "forest green (crayola)",
        "forest green (traditional)",
        "forest green (web)",
        "french beige",
        "french bistre",
        "french blue",
        "french fuchsia",
        "french lilac",
        "french lime",
        "french mauve",
        "french pink",
        "french raspberry",
        "french rose",
        "french sky blue",
        "french violet",
        "frostbite",
        "fuchsia",
        "fuchsia (crayola)",
        "fuchsia purple",
        "fuchsia rose",
        "fulvous",
        "fuzzy wuzzy",
        "gainsboro",
        "gamboge",
        "generic viridian",
        "ghost white",
        "glaucous",
        "glossy grape",
        "go green",
        "gold",
        "gold (crayola)",
        "gold (metallic)",
        "gold (web) (golden)",
        "gold fusion",
        "golden brown",
        "golden poppy",
        "golden yellow",
        "goldenrod",
        "granite gray",
        "granny smith apple",
        "gray (html/css gray)",
        "gray (x11 gray)",
        "green",
        "green (crayola)",
        "green (html/css color)",
        "green (munsell)",
        "green (ncs)",
        "green (pantone)",
        "green (pigment)",
        "green (ryb)",
        "green (x11, color wheel)",
        "green lizard",
        "green sheen",
        "green-blue",
        "green-blue (crayola)",
        "green-cyan",
        "green-yellow",
        "green-yellow (crayola)",
        "grullo",
        "gunmetal",
        "han blue",
        "han purple",
        "hansa yellow",
        "harlequin",
        "harvest gold",
        "heat wave",
        "heliotrope",
        "heliotrope gray",
        "hollywood cerise",
        "honeydew",
        "honolulu blue",
        "hooker's green",
        "hot magenta",
        "hot pink",
        "hunter green",
        "iceberg",
        "icterine",
        "illuminating emerald",
        "imperial red",
        "inchworm",
        "independence",
        "india green",
        "indian red",
        "indian yellow",
        "indigo",
        "indigo blue",
        "indigo dye",
        "international klein blue",
        "international orange (aerospace)",
        "international orange (engineering)",
        "international orange (golden gate bridge)",
        "iris",
        "irresistible",
        "isabelline",
        "islamic green",
        "italian sky blue",
        "ivory",
        "jade",
        "jasmine",
        "jazzberry jam",
        "jet",
        "jonquil",
        "june bud",
        "jungle green",
        "kelly green",
        "keppel",
        "key lime",
        "khaki (html/css) (khaki)",
        "khaki (x11) (light khaki)",
        "kobe",
        "kobi",
        "kobicha",
        "kombu green",
        "ksu purple",
        "languid lavender",
        "lapis lazuli",
        "laser lemon",
        "laurel green",
        "lava",
        "lavender (floral)",
        "lavender (web)",
        "lavender blue",
        "lavender blush",
        "lavender gray",
        "lavender magenta",
        "lawn green",
        "lemon",
        "lemon chiffon",
        "lemon curry",
        "lemon glacier",
        "lemon meringue",
        "lemon yellow",
        "lemon yellow (crayola)",
        "liberty",
        "light apricot",
        "light blue",
        "light brown",
        "light chocolate cosmos",
        "light cobalt blue",
        "light coral",
        "light cornflower blue",
        "light crimson",
        "light cyan",
        "light deep pink",
        "light french beige",
        "light fuchsia pink",
        "light gold",
        "light goldenrod yellow",
        "light gray",
        "light grayish magenta",
        "light green",
        "light hot pink",
        "light khaki",
        "light magenta",
        "light medium orchid",
        "light moss green",
        "light orange",
        "light orchid",
        "light pastel purple",
        "light periwinkle",
        "light pink",
        "light red",
        "light red ochre",
        "light salmon",
        "light salmon pink",
        "light sea green",
        "light silver",
        "light sky blue",
        "light slate gray",
        "light steel blue",
        "light taupe",
        "light yellow",
        "lilac",
        "lilac luster",
        "lime (color wheel)",
        "lime (web) (x11 green)",
        "lime green",
        "lincoln green",
        "linen",
        "lion",
        "liseran purple",
        "little boy blue",
        "little girl pink",
        "liver",
        "liver (dogs)",
        "liver (organ)",
        "liver chestnut",
        "livid",
        "lotion",
        "macaroni and cheese",
        "madder lake",
        "magenta",
        "magenta (crayola)",
        "magenta (dye)",
        "magenta (pantone)",
        "magenta (process)",
        "magenta haze",
        "magic mint",
        "magic potion",
        "magnolia",
        "mahogany",
        "maize",
        "maize (crayola)",
        "majorelle blue",
        "malachite",
        "manatee",
        "mandarin",
        "mango",
        "mango green",
        "mango tango",
        "manila",
        "mantis",
        "maple syrup",
        "mardi gras",
        "margarine",
        "marigold",
        "maroon (crayola)",
        "maroon (html/css)",
        "maroon (x11)",
        "mauve",
        "mauve taupe",
        "mauvelous",
        "maximum blue",
        "maximum blue green",
        "maximum blue purple",
        "maximum green",
        "maximum green yellow",
        "maximum orange",
        "maximum purple",
        "maximum red",
        "maximum red purple",
        "maximum yellow",
        "maximum yellow red",
        "may green",
        "maya blue",
        "medium aquamarine",
        "medium blue",
        "medium candy apple red",
        "medium carmine",
        "medium champagne",
        "medium electric blue",
        "medium jungle green",
        "medium lavender magenta",
        "medium orchid",
        "medium persian blue",
        "medium purple",
        "medium red-violet",
        "medium ruby",
        "medium sea green",
        "medium sky blue",
        "medium slate blue",
        "medium spring bud",
        "medium spring green",
        "medium taupe",
        "medium turquoise",
        "medium tuscan red",
        "medium vermilion",
        "medium violet-red",
        "melancholy",
        "mellow apricot",
        "mellow yellow",
        "melon",
        "metallic gold",
        "metallic seaweed",
        "metallic sunburst",
        "mexican pink",
        "middle blue",
        "middle blue green",
        "middle blue purple",
        "middle green",
        "middle green yellow",
        "middle grey",
        "middle purple",
        "middle red",
        "middle red purple",
        "middle yellow",
        "middle yellow red",
        "midnight",
        "midnight blue",
        "midnight green (eagle green)",
        "mikado yellow",
        "mimi pink",
        "mindaro",
        "ming",
        "minion yellow",
        "mint",
        "mint cream",
        "mint green",
        "misty moss",
        "misty rose",
        "mode beige",
        "morning blue",
        "moss green",
        "mountain meadow",
        "mountbatten pink",
        "msu green",
        "mulberry",
        "mulberry (crayola)",
        "mustard",
        "myrtle green",
        "mystic",
        "mystic maroon",
        "naples yellow",
        "navajo white",
        "navy blue",
        "navy blue (crayola)",
        "neon blue",
        "neon green",
        "new york pink",
        "nickel",
        "nintendo red",
        "non-photo blue",
        "nyanza",
        "ocean blue",
        "ocean green",
        "ochre",
        "office green",
        "old burgundy",
        "old gold",
        "old heliotrope",
        "old lace",
        "old lavender",
        "old mauve",
        "old rose",
        "old silver",
        "olive",
        "olive drab #7",
        "olive drab (#3)",
        "olive green",
        "olivine",
        "onyx",
        "opal",
        "opera mauve",
        "orange",
        "orange (color wheel)",
        "orange (crayola)",
        "orange (pantone)",
        "orange (ryb)",
        "orange (web)",
        "orange peel",
        "orange soda",
        "orange-red",
        "orange-red (crayola)",
        "orange-yellow",
        "orange-yellow (crayola)",
        "orchid",
        "orchid (crayola)",
        "orchid pink",
        "ou crimson red",
        "outer space",
        "outer space (crayola)",
        "outrageous orange",
        "oxblood",
        "oxford blue",
        "pacific blue",
        "pakistan green",
        "palatinate blue",
        "palatinate purple",
        "pale aqua",
        "pale cerulean",
        "pale copper",
        "pale gold",
        "pale goldenrod",
        "pale lavender",
        "pale pink",
        "pale plum",
        "pale purple (pantone)",
        "pale red-violet",
        "pale robin egg blue",
        "pale silver",
        "pale spring bud",
        "pale taupe",
        "pansy purple",
        "paolo veronese green",
        "papaya whip",
        "paradise pink",
        "paris green",
        "pastel pink",
        "patriarch",
        "payne's grey",
        "peach",
        "peach puff",
        "pear",
        "pearl gold",
        "pearly purple",
        "periwinkle",
        "periwinkle (crayola)",
        "permanent geranium lake",
        "persian blue",
        "persian green",
        "persian indigo",
        "persian orange",
        "persian pink",
        "persian plum",
        "persian red",
        "persian rose",
        "persimmon",
        "pewter blue",
        "phlox",
        "phthalo blue",
        "phthalo green",
        "picotee blue",
        "pictorial carmine",
        "piggy pink",
        "pine green",
        "pine tree",
        "pink",
        "pink (pantone)",
        "pink flamingo",
        "pink lace",
        "pink lavender",
        "pink sherbet",
        "pistachio",
        "platinum",
        "plum",
        "plum (web)",
        "plump purple",
        "polished pine",
        "pomp and power",
        "popstar",
        "portland orange",
        "powder blue",
        "princeton orange",
        "prune",
        "prussian blue",
        "psychedelic purple",
        "puce",
        "pullman brown (ups brown)",
        "pumpkin",
        "purple",
        "purple (html)",
        "purple (munsell)",
        "purple (x11)",
        "purple mountain majesty",
        "purple navy",
        "purple pizzazz",
        "purple plum",
        "purpureus",
        "queen blue",
        "queen pink",
        "quick silver",
        "quinacridone magenta",
        "radical red",
        "raisin black",
        "rajah",
        "raspberry",
        "raspberry glace",
        "raspberry rose",
        "raw sienna",
        "raw umber",
        "razzle dazzle rose",
        "razzmatazz",
        "razzmic berry",
        "rebecca purple",
        "red",
        "red (crayola)",
        "red (munsell)",
        "red (ncs)",
        "red (pantone)",
        "red (pigment)",
        "red (ryb)",
        "red salsa",
        "red-orange",
        "red-orange (color wheel)",
        "red-orange (crayola)",
        "red-purple",
        "red-violet",
        "red-violet (color wheel)",
        "red-violet (crayola)",
        "redwood",
        "registration black",
        "resolution blue",
        "rhythm",
        "rich black",
        "rich black (fogra29)",
        "rich black (fogra39)",
        "rich carmine",
        "rich lilac",
        "rich maroon",
        "rifle green",
        "robin egg blue",
        "rocket metallic",
        "roman silver",
        "rose",
        "rose bonbon",
        "rose dust",
        "rose ebony",
        "rose madder",
        "rose pink",
        "rose quartz",
        "rose red",
        "rose taupe",
        "rose vale",
        "rosewood",
        "rosso corsa",
        "rosy brown",
        "royal blue (dark)",
        "royal blue (light)",
        "royal purple",
        "royal yellow",
        "ruber",
        "rubine red",
        "ruby",
        "ruby red",
        "rufous",
        "russet",
        "russian green",
        "russian violet",
        "rust",
        "rusty red",
        "sacramento state green",
        "saddle brown",
        "safety orange",
        "safety orange (blaze orange)",
        "safety yellow",
        "saffron",
        "sage",
        "salmon",
        "salmon pink",
        "sand",
        "sand dune",
        "sandy brown",
        "sandy taupe",
        "sap green",
        "sapphire",
        "sapphire (crayola)",
        "sapphire blue",
        "satin sheen gold",
        "scarlet",
        "schauss pink",
        "school bus yellow",
        "screamin' green",
        "sea green",
        "sea green (crayola)",
        "seal brown",
        "seashell",
        "selective yellow",
        "sepia",
        "shadow",
        "shadow blue",
        "shamrock green",
        "sheen green",
        "shimmering blush",
        "shiny shamrock",
        "shocking pink",
        "shocking pink (crayola)",
        "sienna",
        "silver",
        "silver (crayola)",
        "silver (metallic)",
        "silver chalice",
        "silver foil",
        "silver lake blue",
        "silver pink",
        "silver sand",
        "sinopia",
        "sizzling red",
        "sizzling sunrise",
        "skobeloff",
        "sky blue",
        "sky blue (crayola)",
        "sky magenta",
        "slate blue",
        "slate gray",
        "slimy green",
        "smalt (dark powder blue)",
        "smitten",
        "smoky black",
        "smoky topaz",
        "snow",
        "solid pink",
        "sonic silver",
        "space cadet",
        "spanish bistre",
        "spanish blue",
        "spanish carmine",
        "spanish gray",
        "spanish green",
        "spanish orange",
        "spanish pink",
        "spanish red",
        "spanish sky blue",
        "spanish violet",
        "spanish viridian",
        "spring bud",
        "spring frost",
        "spring green",
        "spring green (crayola)",
        "st. patrick's blue",
        "star command blue",
        "steel blue",
        "steel pink",
        "steel teal",
        "stil de grain yellow",
        "straw",
        "sugar plum",
        "sunglow",
        "sunray",
        "sunset",
        "super pink",
        "sweet brown",
        "tan",
        "tan (crayola)",
        "tangerine",
        "tango pink",
        "tart orange",
        "taupe",
        "taupe gray",
        "tea green",
        "tea rose",
        "teal",
        "teal blue",
        "telemagenta",
        "tenné (tawny)",
        "terra cotta",
        "thistle",
        "thulian pink",
        "tickle me pink",
        "tiffany blue",
        "timberwolf",
        "titanium yellow",
        "tomato",
        "tropical rain forest",
        "true blue",
        "tufts blue",
        "tumbleweed",
        "turquoise",
        "turquoise blue",
        "turquoise green",
        "turtle green",
        "tuscan",
        "tuscan brown",
        "tuscan red",
        "tuscan tan",
        "tuscany",
        "twilight lavender",
        "tyrian purple",
        "ua blue",
        "ua red",
        "ultra pink",
        "ultra red",
        "ultramarine",
        "ultramarine blue",
        "umber",
        "unbleached silk",
        "united nations blue",
        "unmellow yellow",
        "up forest green",
        "up maroon",
        "upsdell red",
        "usafa blue",
        "van dyke brown",
        "vanilla",
        "vanilla ice",
        "vegas gold",
        "venetian red",
        "verdigris",
        "vermilion",
        "veronica",
        "violet",
        "violet (color wheel)",
        "violet (crayola)",
        "violet (ryb)",
        "violet (web)",
        "violet-blue",
        "violet-blue (crayola)",
        "violet-red",
        "viridian",
        "viridian green",
        "vivid burgundy",
        "vivid sky blue",
        "vivid tangerine",
        "vivid violet",
        "volt",
        "warm black",
        "wheat",
        "white",
        "wild blue yonder",
        "wild orchid",
        "wild strawberry",
        "wild watermelon",
        "windsor tan",
        "wine",
        "wine dregs",
        "winter sky",
        "wintergreen dream",
        "wisteria",
        "wood brown",
        "yale blue",
        "yellow",
        "yellow (crayola)",
        "yellow (munsell)",
        "yellow (ncs)",
        "yellow (pantone)",
        "yellow (process)",
        "yellow (ryb)",
        "yellow orange",
        "yellow orange (color wheel)",
        "yellow sunshine",
        "yellow-green",
        "yellow-green (color wheel)",
        "yellow-green (crayola)",
        "yinmn blue",
        "zaffre",
        "zomp"
    )

    private val NAMES: Array<String> = arrayOf(
        "Absolute Zero",
        "Acid",
        "Aero",
        "Air superiority blue",
        "Alabaster",
        "Alice blue",
        "Alloy orange",
        "Almond",
        "Amber",
        "Amethyst",
        "Anti-flash white",
        "Antique brass",
        "Antique bronze",
        "Antique fuchsia",
        "Antique ruby",
        "Antique white",
        "Ao (English)",
        "Apple green",
        "Apricot",
        "Aqua",
        "Aquamarine",
        "Arctic lime",
        "Army green",
        "Artichoke",
        "Arylide yellow",
        "Ash gray",
        "Asparagus",
        "Atomic tangerine",
        "Auburn",
        "Aureolin",
        "Avocado",
        "Azure",
        "B'dazzled blue",
        "Baby blue",
        "Baby blue eyes",
        "Baby pink",
        "Baker-Miller pink",
        "Banana Mania",
        "Barbie Pink",
        "Barbie Pink (Pantone)",
        "Barn red",
        "Battleship grey",
        "Beau blue",
        "Beaver",
        "Beige",
        "Big dip o&rsquo;ruby",
        "Bisque",
        "Bistre",
        "Bistre brown",
        "Bitter lemon",
        "Bitter lime",
        "Bittersweet",
        "Bittersweet shimmer",
        "Black",
        "Black bean",
        "Black chocolate",
        "Black coffee",
        "Black coral",
        "Black olive",
        "Black Shadows",
        "Blanched almond",
        "Blast-off bronze",
        "Bleu de France",
        "Blizzard blue",
        "Blond",
        "Blood red",
        "Blue",
        "Blue (Crayola)",
        "Blue (Munsell)",
        "Blue (NCS)",
        "Blue (Pantone)",
        "Blue (pigment)",
        "Blue (RYB)",
        "Blue bell",
        "Blue jeans",
        "Blue sapphire",
        "Blue yonder",
        "Blue-gray",
        "Blue-green",
        "Blue-green (color wheel)",
        "Blue-violet",
        "Blue-violet (color wheel)",
        "Blue-violet (Crayola)",
        "Bluetiful",
        "Blush",
        "Bole",
        "Bondi blue",
        "Bone",
        "Bottle green",
        "Brandy",
        "Brick red",
        "Bright green",
        "Bright lilac",
        "Bright maroon",
        "Bright navy blue",
        "Bright pink",
        "Bright yellow (Crayola)",
        "Brilliant rose",
        "Brink pink",
        "British racing green",
        "Bronze",
        "Brown",
        "Brown sugar",
        "Brunswick green",
        "Bubbles",
        "Bud green",
        "Buff",
        "Burgundy",
        "Burlywood",
        "Burnished brown",
        "Burnt orange",
        "Burnt sienna",
        "Burnt umber",
        "Byzantine",
        "Byzantium",
        "Cadet",
        "Cadet blue",
        "Cadet blue (Crayola)",
        "Cadet grey",
        "Cadmium green",
        "Cadmium orange",
        "Cadmium red",
        "Cadmium yellow",
        "Caf&eacute; au lait",
        "Caf&eacute; noir",
        "Cal Poly Pomona green",
        "Cambridge blue",
        "Camel",
        "Cameo pink",
        "Canary",
        "Canary yellow",
        "Candy apple red",
        "Candy pink",
        "Capri",
        "Caput mortuum",
        "Cardinal",
        "Caribbean green",
        "Carmine",
        "Carmine (M&amp;P)",
        "Carnation pink",
        "Carnelian",
        "Carolina blue",
        "Carrot orange",
        "Castleton green",
        "Catawba",
        "Cedar Chest",
        "Celadon",
        "Celadon blue",
        "Celadon green",
        "Celeste",
        "Celtic blue",
        "Cerise",
        "Cerulean",
        "Cerulean (Crayola)",
        "Cerulean blue",
        "Cerulean frost",
        "CG blue",
        "CG red",
        "Champagne",
        "Champagne pink",
        "Charcoal",
        "Charleston green",
        "Charm pink",
        "Chartreuse (traditional)",
        "Chartreuse (web)",
        "Cherry blossom pink",
        "Chestnut",
        "China pink",
        "China rose",
        "Chinese red",
        "Chinese violet",
        "Chinese yellow",
        "Chocolate (traditional)",
        "Chocolate (web)",
        "Chrome yellow",
        "Cinereous",
        "Cinnabar",
        "Cinnamon Satin",
        "Citrine",
        "Citron",
        "Claret",
        "Cobalt blue",
        "Cocoa brown",
        "Coffee",
        "Columbia Blue",
        "Congo pink",
        "Cool grey",
        "Copper",
        "Copper (Crayola)",
        "Copper penny",
        "Copper red",
        "Copper rose",
        "Coquelicot",
        "Coral",
        "Coral pink",
        "Cordovan",
        "Corn",
        "Cornflower blue",
        "Cornsilk",
        "Cosmic cobalt",
        "Cosmic latte",
        "Cosmos pink",
        "Cotton candy",
        "Coyote brown",
        "Cream",
        "Crimson",
        "Cultured",
        "Cyan",
        "Cyan (process)",
        "Cyber grape",
        "Cyber yellow",
        "Cyclamen",
        "Dark blue-gray",
        "Dark brown",
        "Dark byzantium",
        "Dark cornflower blue",
        "Dark cyan",
        "Dark electric blue",
        "Dark goldenrod",
        "Dark green",
        "Dark green (X11)",
        "Dark jungle green",
        "Dark khaki",
        "Dark lava",
        "Dark liver",
        "Dark liver (horses)",
        "Dark magenta",
        "Dark medium gray",
        "Dark moss green",
        "Dark olive green",
        "Dark orange",
        "Dark orchid",
        "Dark pastel green",
        "Dark purple",
        "Dark red",
        "Dark salmon",
        "Dark sea green",
        "Dark sienna",
        "Dark sky blue",
        "Dark slate blue",
        "Dark slate gray",
        "Dark spring green",
        "Dark turquoise",
        "Dark violet",
        "Dartmouth green",
        "Davy's grey",
        "Deep cerise",
        "Deep champagne",
        "Deep chestnut",
        "Deep fuchsia",
        "Deep jungle green",
        "Deep pink",
        "Deep saffron",
        "Deep sky blue",
        "Deep Space Sparkle",
        "Deep taupe",
        "Denim",
        "Denim blue",
        "Desert",
        "Desert sand",
        "Dim gray",
        "Dodger blue",
        "Dogwood rose",
        "Drab",
        "Duke blue",
        "Dutch white",
        "Earth yellow",
        "Ebony",
        "Ecru",
        "Eerie black",
        "Eggplant",
        "Eggshell",
        "Egyptian blue",
        "Electric blue",
        "Electric green",
        "Electric indigo",
        "Electric lime",
        "Electric purple",
        "Electric violet",
        "Emerald",
        "Eminence",
        "English green",
        "English lavender",
        "English red",
        "English vermillion",
        "English violet",
        "Erin",
        "Eton blue",
        "Fallow",
        "Falu red",
        "Fandango",
        "Fandango pink",
        "Fashion fuchsia",
        "Fawn",
        "Feldgrau",
        "Fern green",
        "Field drab",
        "Fiery rose",
        "Fire engine red",
        "Fire opal",
        "Firebrick",
        "Flame",
        "Flavescent",
        "Flax",
        "Flesh",
        "Flirt",
        "Floral white",
        "Fluorescent blue",
        "Forest green (Crayola)",
        "Forest green (traditional)",
        "Forest green (web)",
        "French beige",
        "French bistre",
        "French blue",
        "French fuchsia",
        "French lilac",
        "French lime",
        "French mauve",
        "French pink",
        "French raspberry",
        "French rose",
        "French sky blue",
        "French violet",
        "Frostbite",
        "Fuchsia",
        "Fuchsia (Crayola)",
        "Fuchsia purple",
        "Fuchsia rose",
        "Fulvous",
        "Fuzzy Wuzzy",
        "Gainsboro",
        "Gamboge",
        "Generic viridian",
        "Ghost white",
        "Glaucous",
        "Glossy grape",
        "GO green",
        "Gold",
        "Gold (Crayola)",
        "Gold (metallic)",
        "Gold (web) (Golden)",
        "Gold Fusion",
        "Golden brown",
        "Golden poppy",
        "Golden yellow",
        "Goldenrod",
        "Granite gray",
        "Granny Smith apple",
        "Gray (HTML/CSS gray)",
        "Gray (X11 gray)",
        "Green",
        "Green (Crayola)",
        "Green (HTML/CSS color)",
        "Green (Munsell)",
        "Green (NCS)",
        "Green (Pantone)",
        "Green (pigment)",
        "Green (RYB)",
        "Green (X11, color wheel)",
        "Green Lizard",
        "Green Sheen",
        "Green-blue",
        "Green-blue (Crayola)",
        "Green-cyan",
        "Green-yellow",
        "Green-yellow (Crayola)",
        "Grullo",
        "Gunmetal",
        "Han blue",
        "Han purple",
        "Hansa yellow",
        "Harlequin",
        "Harvest gold",
        "Heat Wave",
        "Heliotrope",
        "Heliotrope gray",
        "Hollywood cerise",
        "Honeydew",
        "Honolulu blue",
        "Hooker's green",
        "Hot magenta",
        "Hot pink",
        "Hunter green",
        "Iceberg",
        "Icterine",
        "Illuminating emerald",
        "Imperial red",
        "Inchworm",
        "Independence",
        "India green",
        "Indian red",
        "Indian yellow",
        "Indigo",
        "Indigo blue",
        "Indigo dye",
        "International Klein Blue",
        "International orange (aerospace)",
        "International orange (engineering)",
        "International orange (Golden Gate Bridge)",
        "Iris",
        "Irresistible",
        "Isabelline",
        "Islamic green",
        "Italian sky blue",
        "Ivory",
        "Jade",
        "Jasmine",
        "Jazzberry jam",
        "Jet",
        "Jonquil",
        "June bud",
        "Jungle green",
        "Kelly green",
        "Keppel",
        "Key lime",
        "Khaki (HTML/CSS) (Khaki)",
        "Khaki (X11) (Light khaki)",
        "Kobe",
        "Kobi",
        "Kobicha",
        "Kombu green",
        "KSU purple",
        "Languid lavender",
        "Lapis lazuli",
        "Laser lemon",
        "Laurel green",
        "Lava",
        "Lavender (floral)",
        "Lavender (web)",
        "Lavender blue",
        "Lavender blush",
        "Lavender gray",
        "Lavender magenta",
        "Lawn green",
        "Lemon",
        "Lemon chiffon",
        "Lemon curry",
        "Lemon glacier",
        "Lemon meringue",
        "Lemon yellow",
        "Lemon yellow (Crayola)",
        "Liberty",
        "Light apricot",
        "Light blue",
        "Light brown",
        "Light chocolate cosmos",
        "Light cobalt blue",
        "Light coral",
        "Light cornflower blue",
        "Light crimson",
        "Light cyan",
        "Light deep pink",
        "Light French beige",
        "Light fuchsia pink",
        "Light gold",
        "Light goldenrod yellow",
        "Light gray",
        "Light grayish magenta",
        "Light green",
        "Light hot pink",
        "Light khaki",
        "Light magenta",
        "Light medium orchid",
        "Light moss green",
        "Light orange",
        "Light orchid",
        "Light pastel purple",
        "Light periwinkle",
        "Light pink",
        "Light red",
        "Light red ochre",
        "Light salmon",
        "Light salmon pink",
        "Light sea green",
        "Light silver",
        "Light sky blue",
        "Light slate gray",
        "Light steel blue",
        "Light taupe",
        "Light yellow",
        "Lilac",
        "Lilac Luster",
        "Lime (color wheel)",
        "Lime (web) (X11 green)",
        "Lime green",
        "Lincoln green",
        "Linen",
        "Lion",
        "Liseran purple",
        "Little boy blue",
        "Little girl pink",
        "Liver",
        "Liver (dogs)",
        "Liver (organ)",
        "Liver chestnut",
        "Livid",
        "Lotion",
        "Macaroni and Cheese",
        "Madder Lake",
        "Magenta",
        "Magenta (Crayola)",
        "Magenta (dye)",
        "Magenta (Pantone)",
        "Magenta (process)",
        "Magenta haze",
        "Magic mint",
        "Magic Potion",
        "Magnolia",
        "Mahogany",
        "Maize",
        "Maize (Crayola)",
        "Majorelle blue",
        "Malachite",
        "Manatee",
        "Mandarin",
        "Mango",
        "Mango green",
        "Mango Tango",
        "Manila",
        "Mantis",
        "Maple syrup",
        "Mardi Gras",
        "Margarine",
        "Marigold",
        "Maroon (Crayola)",
        "Maroon (HTML/CSS)",
        "Maroon (X11)",
        "Mauve",
        "Mauve taupe",
        "Mauvelous",
        "Maximum blue",
        "Maximum blue green",
        "Maximum blue purple",
        "Maximum green",
        "Maximum green yellow",
        "Maximum orange",
        "Maximum purple",
        "Maximum red",
        "Maximum red purple",
        "Maximum yellow",
        "Maximum yellow red",
        "May green",
        "Maya blue",
        "Medium aquamarine",
        "Medium blue",
        "Medium candy apple red",
        "Medium carmine",
        "Medium champagne",
        "Medium electric blue",
        "Medium jungle green",
        "Medium lavender magenta",
        "Medium orchid",
        "Medium Persian blue",
        "Medium purple",
        "Medium red-violet",
        "Medium ruby",
        "Medium sea green",
        "Medium sky blue",
        "Medium slate blue",
        "Medium spring bud",
        "Medium spring green",
        "Medium taupe",
        "Medium turquoise",
        "Medium Tuscan red",
        "Medium vermilion",
        "Medium violet-red",
        "Melancholy",
        "Mellow apricot",
        "Mellow yellow",
        "Melon",
        "Metallic gold",
        "Metallic Seaweed",
        "Metallic Sunburst",
        "Mexican pink",
        "Middle blue",
        "Middle blue green",
        "Middle blue purple",
        "Middle green",
        "Middle green yellow",
        "Middle grey",
        "Middle purple",
        "Middle red",
        "Middle red purple",
        "Middle yellow",
        "Middle yellow red",
        "Midnight",
        "Midnight blue",
        "Midnight green (eagle green)",
        "Mikado yellow",
        "Mimi pink",
        "Mindaro",
        "Ming",
        "Minion yellow",
        "Mint",
        "Mint cream",
        "Mint green",
        "Misty moss",
        "Misty rose",
        "Mode beige",
        "Morning blue",
        "Moss green",
        "Mountain Meadow",
        "Mountbatten pink",
        "MSU green",
        "Mulberry",
        "Mulberry (Crayola)",
        "Mustard",
        "Myrtle green",
        "Mystic",
        "Mystic maroon",
        "Naples yellow",
        "Navajo white",
        "Navy blue",
        "Navy blue (Crayola)",
        "Neon blue",
        "Neon green",
        "New York pink",
        "Nickel",
        "Nintendo red",
        "Non-photo blue",
        "Nyanza",
        "Ocean Blue",
        "Ocean green",
        "Ochre",
        "Office green",
        "Old burgundy",
        "Old gold",
        "Old heliotrope",
        "Old lace",
        "Old lavender",
        "Old mauve",
        "Old rose",
        "Old silver",
        "Olive",
        "Olive Drab #7",
        "Olive Drab (#3)",
        "Olive green",
        "Olivine",
        "Onyx",
        "Opal",
        "Opera mauve",
        "Orange",
        "Orange (color wheel)",
        "Orange (Crayola)",
        "Orange (Pantone)",
        "Orange (RYB)",
        "Orange (web)",
        "Orange peel",
        "Orange soda",
        "Orange-red",
        "Orange-red (Crayola)",
        "Orange-yellow",
        "Orange-yellow (Crayola)",
        "Orchid",
        "Orchid (Crayola)",
        "Orchid pink",
        "OU Crimson red",
        "Outer space",
        "Outer space (Crayola)",
        "Outrageous Orange",
        "Oxblood",
        "Oxford blue",
        "Pacific blue",
        "Pakistan green",
        "Palatinate blue",
        "Palatinate purple",
        "Pale aqua",
        "Pale cerulean",
        "Pale copper",
        "Pale gold",
        "Pale goldenrod",
        "Pale lavender",
        "Pale pink",
        "Pale plum",
        "Pale purple (Pantone)",
        "Pale red-violet",
        "Pale robin egg blue",
        "Pale silver",
        "Pale spring bud",
        "Pale taupe",
        "Pansy purple",
        "Paolo Veronese green",
        "Papaya whip",
        "Paradise pink",
        "Paris Green",
        "Pastel pink",
        "Patriarch",
        "Payne's grey",
        "Peach",
        "Peach puff",
        "Pear",
        "Pearl gold",
        "Pearly purple",
        "Periwinkle",
        "Periwinkle (Crayola)",
        "Permanent Geranium Lake",
        "Persian blue",
        "Persian green",
        "Persian indigo",
        "Persian orange",
        "Persian pink",
        "Persian plum",
        "Persian red",
        "Persian rose",
        "Persimmon",
        "Pewter Blue",
        "Phlox",
        "Phthalo blue",
        "Phthalo green",
        "Picotee blue",
        "Pictorial carmine",
        "Piggy pink",
        "Pine green",
        "Pine tree",
        "Pink",
        "Pink (Pantone)",
        "Pink flamingo",
        "Pink lace",
        "Pink lavender",
        "Pink Sherbet",
        "Pistachio",
        "Platinum",
        "Plum",
        "Plum (web)",
        "Plump Purple",
        "Polished Pine",
        "Pomp and Power",
        "Popstar",
        "Portland Orange",
        "Powder blue",
        "Princeton orange",
        "Prune",
        "Prussian blue",
        "Psychedelic purple",
        "Puce",
        "Pullman Brown (UPS Brown)",
        "Pumpkin",
        "Purple",
        "Purple (HTML)",
        "Purple (Munsell)",
        "Purple (X11)",
        "Purple mountain majesty",
        "Purple navy",
        "Purple pizzazz",
        "Purple Plum",
        "Purpureus",
        "Queen blue",
        "Queen pink",
        "Quick Silver",
        "Quinacridone magenta",
        "Radical Red",
        "Raisin black",
        "Rajah",
        "Raspberry",
        "Raspberry glace",
        "Raspberry rose",
        "Raw Sienna",
        "Raw umber",
        "Razzle dazzle rose",
        "Razzmatazz",
        "Razzmic Berry",
        "Rebecca Purple",
        "Red",
        "Red (Crayola)",
        "Red (Munsell)",
        "Red (NCS)",
        "Red (Pantone)",
        "Red (pigment)",
        "Red (RYB)",
        "Red Salsa",
        "Red-orange",
        "Red-orange (color wheel)",
        "Red-orange (Crayola)",
        "Red-purple",
        "Red-violet",
        "Red-violet (color wheel)",
        "Red-violet (Crayola)",
        "Redwood",
        "Registration black",
        "Resolution blue",
        "Rhythm",
        "Rich black",
        "Rich black (FOGRA29)",
        "Rich black (FOGRA39)",
        "Rich carmine",
        "Rich lilac",
        "Rich maroon",
        "Rifle green",
        "Robin egg blue",
        "Rocket metallic",
        "Roman silver",
        "Rose",
        "Rose bonbon",
        "Rose Dust",
        "Rose ebony",
        "Rose madder",
        "Rose pink",
        "Rose quartz",
        "Rose red",
        "Rose taupe",
        "Rose vale",
        "Rosewood",
        "Rosso corsa",
        "Rosy brown",
        "Royal blue (dark)",
        "Royal blue (light)",
        "Royal purple",
        "Royal yellow",
        "Ruber",
        "Rubine red",
        "Ruby",
        "Ruby red",
        "Rufous",
        "Russet",
        "Russian green",
        "Russian violet",
        "Rust",
        "Rusty red",
        "Sacramento State green",
        "Saddle brown",
        "Safety orange",
        "Safety orange (blaze orange)",
        "Safety yellow",
        "Saffron",
        "Sage",
        "Salmon",
        "Salmon pink",
        "Sand",
        "Sand dune",
        "Sandy brown",
        "Sandy taupe",
        "Sap green",
        "Sapphire",
        "Sapphire (Crayola)",
        "Sapphire blue",
        "Satin sheen gold",
        "Scarlet",
        "Schauss pink",
        "School bus yellow",
        "Screamin' Green",
        "Sea green",
        "Sea green (Crayola)",
        "Seal brown",
        "Seashell",
        "Selective yellow",
        "Sepia",
        "Shadow",
        "Shadow blue",
        "Shamrock green",
        "Sheen green",
        "Shimmering Blush",
        "Shiny Shamrock",
        "Shocking pink",
        "Shocking pink (Crayola)",
        "Sienna",
        "Silver",
        "Silver (Crayola)",
        "Silver (Metallic)",
        "Silver chalice",
        "Silver foil",
        "Silver Lake blue",
        "Silver pink",
        "Silver sand",
        "Sinopia",
        "Sizzling Red",
        "Sizzling Sunrise",
        "Skobeloff",
        "Sky blue",
        "Sky blue (Crayola)",
        "Sky magenta",
        "Slate blue",
        "Slate gray",
        "Slimy green",
        "Smalt (Dark powder blue)",
        "Smitten",
        "Smoky black",
        "Smoky Topaz",
        "Snow",
        "Solid pink",
        "Sonic silver",
        "Space cadet",
        "Spanish bistre",
        "Spanish blue",
        "Spanish carmine",
        "Spanish gray",
        "Spanish green",
        "Spanish orange",
        "Spanish pink",
        "Spanish red",
        "Spanish sky blue",
        "Spanish violet",
        "Spanish viridian",
        "Spring bud",
        "Spring Frost",
        "Spring green",
        "Spring green (Crayola)",
        "St. Patrick's blue",
        "Star command blue",
        "Steel blue",
        "Steel pink",
        "Steel Teal",
        "Stil de grain yellow",
        "Straw",
        "Sugar Plum",
        "Sunglow",
        "Sunray",
        "Sunset",
        "Super pink",
        "Sweet Brown",
        "Tan",
        "Tan (Crayola)",
        "Tangerine",
        "Tango pink",
        "Tart Orange",
        "Taupe",
        "Taupe gray",
        "Tea green",
        "Tea rose",
        "Teal",
        "Teal blue",
        "Telemagenta",
        "Tenné (tawny)",
        "Terra cotta",
        "Thistle",
        "Thulian pink",
        "Tickle Me Pink",
        "Tiffany Blue",
        "Timberwolf",
        "Titanium yellow",
        "Tomato",
        "Tropical rain forest",
        "True Blue",
        "Tufts blue",
        "Tumbleweed",
        "Turquoise",
        "Turquoise blue",
        "Turquoise green",
        "Turtle green",
        "Tuscan",
        "Tuscan brown",
        "Tuscan red",
        "Tuscan tan",
        "Tuscany",
        "Twilight lavender",
        "Tyrian purple",
        "UA blue",
        "UA red",
        "Ultra pink",
        "Ultra red",
        "Ultramarine",
        "Ultramarine blue",
        "Umber",
        "Unbleached silk",
        "United Nations blue",
        "Unmellow yellow",
        "UP Forest green",
        "UP maroon",
        "Upsdell red",
        "USAFA blue",
        "Van Dyke brown",
        "Vanilla",
        "Vanilla ice",
        "Vegas gold",
        "Venetian red",
        "Verdigris",
        "Vermilion",
        "Veronica",
        "Violet",
        "Violet (color wheel)",
        "Violet (crayola)",
        "Violet (RYB)",
        "Violet (web)",
        "Violet-blue",
        "Violet-blue (Crayola)",
        "Violet-red",
        "Viridian",
        "Viridian green",
        "Vivid burgundy",
        "Vivid sky blue",
        "Vivid tangerine",
        "Vivid violet",
        "Volt",
        "Warm black",
        "Wheat",
        "White",
        "Wild blue yonder",
        "Wild orchid",
        "Wild Strawberry",
        "Wild watermelon",
        "Windsor tan",
        "Wine",
        "Wine dregs",
        "Winter Sky",
        "Wintergreen Dream",
        "Wisteria",
        "Wood brown",
        "Yale Blue",
        "Yellow",
        "Yellow (Crayola)",
        "Yellow (Munsell)",
        "Yellow (NCS)",
        "Yellow (Pantone)",
        "Yellow (process)",
        "Yellow (RYB)",
        "Yellow Orange",
        "Yellow Orange (color wheel)",
        "Yellow Sunshine",
        "Yellow-green",
        "Yellow-green (color wheel)",
        "Yellow-green (Crayola)",
        "YInMn Blue",
        "Zaffre",
        "Zomp"
    )

    private val ARGB: IntArray = intArrayOf(
        0xFF0048BA.toInt(),
        0xFFB0BF1A.toInt(),
        0xFF7CB9E8.toInt(),
        0xFF72A0C1.toInt(),
        0xFFEDEAE0.toInt(),
        0xFFF0F8FF.toInt(),
        0xFFC46210.toInt(),
        0xFFEFDECD.toInt(),
        0xFFFFBF00.toInt(),
        0xFF9966CC.toInt(),
        0xFFF2F3F4.toInt(),
        0xFFCD9575.toInt(),
        0xFF665D1E.toInt(),
        0xFF915C83.toInt(),
        0xFF841B2D.toInt(),
        0xFFFAEBD7.toInt(),
        0xFF008000.toInt(),
        0xFF8DB600.toInt(),
        0xFFFBCEB1.toInt(),
        0xFF00FFFF.toInt(),
        0xFF7FFFD4.toInt(),
        0xFFD0FF14.toInt(),
        0xFF4B5320.toInt(),
        0xFF8F9779.toInt(),
        0xFFE9D66B.toInt(),
        0xFFB2BEB5.toInt(),
        0xFF87A96B.toInt(),
        0xFFFF9966.toInt(),
        0xFFA52A2A.toInt(),
        0xFFFDEE00.toInt(),
        0xFF568203.toInt(),
        0xFF007FFF.toInt(),
        0xFF2E5894.toInt(),
        0xFF89CFF0.toInt(),
        0xFFA1CAF1.toInt(),
        0xFFF4C2C2.toInt(),
        0xFFFF91AF.toInt(),
        0xFFFAE7B5.toInt(),
        0xFFE94196.toInt(),
        0xFFE0218A.toInt(),
        0xFF7C0A02.toInt(),
        0xFF848482.toInt(),
        0xFFBCD4E6.toInt(),
        0xFF9F8170.toInt(),
        0xFFF5F5DC.toInt(),
        0xFF9C2542.toInt(),
        0xFFFFE4C4.toInt(),
        0xFF3D2B1F.toInt(),
        0xFF967117.toInt(),
        0xFFCAE00D.toInt(),
        0xFFBFFF00.toInt(),
        0xFFFE6F5E.toInt(),
        0xFFBF4F51.toInt(),
        0xFF000000.toInt(),
        0xFF3D0C02.toInt(),
        0xFF1B1811.toInt(),
        0xFF3B2F2F.toInt(),
        0xFF54626F.toInt(),
        0xFF3B3C36.toInt(),
        0xFFBFAFB2.toInt(),
        0xFFFFEBCD.toInt(),
        0xFFA57164.toInt(),
        0xFF318CE7.toInt(),
        0xFFACE5EE.toInt(),
        0xFFFAF0BE.toInt(),
        0xFF660000.toInt(),
        0xFF0000FF.toInt(),
        0xFF1F75FE.toInt(),
        0xFF0093AF.toInt(),
        0xFF0087BD.toInt(),
        0xFF0018A8.toInt(),
        0xFF333399.toInt(),
        0xFF0247FE.toInt(),
        0xFFA2A2D0.toInt(),
        0xFF5DADEC.toInt(),
        0xFF126180.toInt(),
        0xFF5072A7.toInt(),
        0xFF6699CC.toInt(),
        0xFF0D98BA.toInt(),
        0xFF064E40.toInt(),
        0xFF8A2BE2.toInt(),
        0xFF4D1A7F.toInt(),
        0xFF7366BD.toInt(),
        0xFF3C69E7.toInt(),
        0xFFDE5D83.toInt(),
        0xFF79443B.toInt(),
        0xFF0095B6.toInt(),
        0xFFE3DAC9.toInt(),
        0xFF006A4E.toInt(),
        0xFF87413F.toInt(),
        0xFFCB4154.toInt(),
        0xFF66FF00.toInt(),
        0xFFD891EF.toInt(),
        0xFFC32148.toInt(),
        0xFF1974D2.toInt(),
        0xFFFF007F.toInt(),
        0xFFFFAA1D.toInt(),
        0xFFFF55A3.toInt(),
        0xFFFB607F.toInt(),
        0xFF004225.toInt(),
        0xFFCD7F32.toInt(),
        0xFF88540B.toInt(),
        0xFFAF6E4D.toInt(),
        0xFF1B4D3E.toInt(),
        0xFFE7FEFF.toInt(),
        0xFF7BB661.toInt(),
        0xFFF0DC82.toInt(),
        0xFF800020.toInt(),
        0xFFDEB887.toInt(),
        0xFFA17A74.toInt(),
        0xFFCC5500.toInt(),
        0xFFE97451.toInt(),
        0xFF8A3324.toInt(),
        0xFFBD33A4.toInt(),
        0xFF702963.toInt(),
        0xFF536872.toInt(),
        0xFF5F9EA0.toInt(),
        0xFFA9B2C3.toInt(),
        0xFF91A3B0.toInt(),
        0xFF006B3C.toInt(),
        0xFFED872D.toInt(),
        0xFFE30022.toInt(),
        0xFFFFF600.toInt(),
        0xFFA67B5B.toInt(),
        0xFF4B3621.toInt(),
        0xFF1E4D2B.toInt(),
        0xFFA3C1AD.toInt(),
        0xFFC19A6B.toInt(),
        0xFFEFBBCC.toInt(),
        0xFFFFFF99.toInt(),
        0xFFFFEF00.toInt(),
        0xFFFF0800.toInt(),
        0xFFE4717A.toInt(),
        0xFF00BFFF.toInt(),
        0xFF592720.toInt(),
        0xFFC41E3A.toInt(),
        0xFF00CC99.toInt(),
        0xFF960018.toInt(),
        0xFFD70040.toInt(),
        0xFFFFA6C9.toInt(),
        0xFFB31B1B.toInt(),
        0xFF56A0D3.toInt(),
        0xFFED9121.toInt(),
        0xFF00563F.toInt(),
        0xFF703642.toInt(),
        0xFFC95A49.toInt(),
        0xFFACE1AF.toInt(),
        0xFF007BA7.toInt(),
        0xFF2F847C.toInt(),
        0xFFB2FFFF.toInt(),
        0xFF246BCE.toInt(),
        0xFFDE3163.toInt(),
        0xFF007BA7.toInt(),
        0xFF1DACD6.toInt(),
        0xFF2A52BE.toInt(),
        0xFF6D9BC3.toInt(),
        0xFF007AA5.toInt(),
        0xFFE03C31.toInt(),
        0xFFF7E7CE.toInt(),
        0xFFF1DDCF.toInt(),
        0xFF36454F.toInt(),
        0xFF232B2B.toInt(),
        0xFFE68FAC.toInt(),
        0xFFDFFF00.toInt(),
        0xFF7FFF00.toInt(),
        0xFFFFB7C5.toInt(),
        0xFF954535.toInt(),
        0xFFDE6FA1.toInt(),
        0xFFA8516E.toInt(),
        0xFFAA381E.toInt(),
        0xFF856088.toInt(),
        0xFFFFB200.toInt(),
        0xFF7B3F00.toInt(),
        0xFFD2691E.toInt(),
        0xFFFFA700.toInt(),
        0xFF98817B.toInt(),
        0xFFE34234.toInt(),
        0xFFCD607E.toInt(),
        0xFFE4D00A.toInt(),
        0xFF9FA91F.toInt(),
        0xFF7F1734.toInt(),
        0xFF0047AB.toInt(),
        0xFFD2691E.toInt(),
        0xFF6F4E37.toInt(),
        0xFFB9D9EB.toInt(),
        0xFFF88379.toInt(),
        0xFF8C92AC.toInt(),
        0xFFB87333.toInt(),
        0xFFDA8A67.toInt(),
        0xFFAD6F69.toInt(),
        0xFFCB6D51.toInt(),
        0xFF996666.toInt(),
        0xFFFF3800.toInt(),
        0xFFFF7F50.toInt(),
        0xFFF88379.toInt(),
        0xFF893F45.toInt(),
        0xFFFBEC5D.toInt(),
        0xFF6495ED.toInt(),
        0xFFFFF8DC.toInt(),
        0xFF2E2D88.toInt(),
        0xFFFFF8E7.toInt(),
        0xFFFEBCFF.toInt(),
        0xFFFFBCD9.toInt(),
        0xFF81613C.toInt(),
        0xFFFFFDD0.toInt(),
        0xFFDC143C.toInt(),
        0xFFF5F5F5.toInt(),
        0xFF00FFFF.toInt(),
        0xFF00B7EB.toInt(),
        0xFF58427C.toInt(),
        0xFFFFD300.toInt(),
        0xFFF56FA1.toInt(),
        0xFF666699.toInt(),
        0xFF654321.toInt(),
        0xFF5D3954.toInt(),
        0xFF26428B.toInt(),
        0xFF008B8B.toInt(),
        0xFF536878.toInt(),
        0xFFB8860B.toInt(),
        0xFF013220.toInt(),
        0xFF006400.toInt(),
        0xFF1A2421.toInt(),
        0xFFBDB76B.toInt(),
        0xFF483C32.toInt(),
        0xFF534B4F.toInt(),
        0xFF543D37.toInt(),
        0xFF8B008B.toInt(),
        0xFFA9A9A9.toInt(),
        0xFF4A5D23.toInt(),
        0xFF556B2F.toInt(),
        0xFFFF8C00.toInt(),
        0xFF9932CC.toInt(),
        0xFF03C03C.toInt(),
        0xFF301934.toInt(),
        0xFF8B0000.toInt(),
        0xFFE9967A.toInt(),
        0xFF8FBC8F.toInt(),
        0xFF3C1414.toInt(),
        0xFF8CBED6.toInt(),
        0xFF483D8B.toInt(),
        0xFF2F4F4F.toInt(),
        0xFF177245.toInt(),
        0xFF00CED1.toInt(),
        0xFF9400D3.toInt(),
        0xFF00703C.toInt(),
        0xFF555555.toInt(),
        0xFFDA3287.toInt(),
        0xFFFAD6A5.toInt(),
        0xFFB94E48.toInt(),
        0xFFC154C1.toInt(),
        0xFF004B49.toInt(),
        0xFFFF1493.toInt(),
        0xFFFF9933.toInt(),
        0xFF00BFFF.toInt(),
        0xFF4A646C.toInt(),
        0xFF7E5E60.toInt(),
        0xFF1560BD.toInt(),
        0xFF2243B6.toInt(),
        0xFFC19A6B.toInt(),
        0xFFEDC9AF.toInt(),
        0xFF696969.toInt(),
        0xFF1E90FF.toInt(),
        0xFFD71868.toInt(),
        0xFF967117.toInt(),
        0xFF00009C.toInt(),
        0xFFEFDFBB.toInt(),
        0xFFE1A95F.toInt(),
        0xFF555D50.toInt(),
        0xFFC2B280.toInt(),
        0xFF1B1B1B.toInt(),
        0xFF614051.toInt(),
        0xFFF0EAD6.toInt(),
        0xFF1034A6.toInt(),
        0xFF7DF9FF.toInt(),
        0xFF00FF00.toInt(),
        0xFF6F00FF.toInt(),
        0xFFCCFF00.toInt(),
        0xFFBF00FF.toInt(),
        0xFF8F00FF.toInt(),
        0xFF50C878.toInt(),
        0xFF6C3082.toInt(),
        0xFF1B4D3E.toInt(),
        0xFFB48395.toInt(),
        0xFFAB4B52.toInt(),
        0xFFCC474B.toInt(),
        0xFF563C5C.toInt(),
        0xFF00FF40.toInt(),
        0xFF96C8A2.toInt(),
        0xFFC19A6B.toInt(),
        0xFF801818.toInt(),
        0xFFB53389.toInt(),
        0xFFDE5285.toInt(),
        0xFFF400A1.toInt(),
        0xFFE5AA70.toInt(),
        0xFF4D5D53.toInt(),
        0xFF4F7942.toInt(),
        0xFF6C541E.toInt(),
        0xFFFF5470.toInt(),
        0xFFCE2029.toInt(),
        0xFFE95C4B.toInt(),
        0xFFB22222.toInt(),
        0xFFE25822.toInt(),
        0xFFF7E98E.toInt(),
        0xFFEEDC82.toInt(),
        0xFFFFE9D1.toInt(),
        0xFFA2006D.toInt(),
        0xFFFFFAF0.toInt(),
        0xFF15F4EE.toInt(),
        0xFF5FA777.toInt(),
        0xFF014421.toInt(),
        0xFF228B22.toInt(),
        0xFFA67B5B.toInt(),
        0xFF856D4D.toInt(),
        0xFF0072BB.toInt(),
        0xFFFD3F92.toInt(),
        0xFF86608E.toInt(),
        0xFF9EFD38.toInt(),
        0xFFD473D4.toInt(),
        0xFFFD6C9E.toInt(),
        0xFFC72C48.toInt(),
        0xFFF64A8A.toInt(),
        0xFF77B5FE.toInt(),
        0xFF8806CE.toInt(),
        0xFFE936A7.toInt(),
        0xFFFF00FF.toInt(),
        0xFFC154C1.toInt(),
        0xFFCC397B.toInt(),
        0xFFC74375.toInt(),
        0xFFE48400.toInt(),
        0xFFCC6666.toInt(),
        0xFFDCDCDC.toInt(),
        0xFFE49B0F.toInt(),
        0xFF007F66.toInt(),
        0xFFF8F8FF.toInt(),
        0xFF6082B6.toInt(),
        0xFFAB92B3.toInt(),
        0xFF00AB66.toInt(),
        0xFFA57C00.toInt(),
        0xFFE6BE8A.toInt(),
        0xFFD4AF37.toInt(),
        0xFFFFD700.toInt(),
        0xFF85754E.toInt(),
        0xFF996515.toInt(),
        0xFFFCC200.toInt(),
        0xFFFFDF00.toInt(),
        0xFFDAA520.toInt(),
        0xFF676767.toInt(),
        0xFFA8E4A0.toInt(),
        0xFF808080.toInt(),
        0xFFBEBEBE.toInt(),
        0xFF00FF00.toInt(),
        0xFF1CAC78.toInt(),
        0xFF008000.toInt(),
        0xFF00A877.toInt(),
        0xFF009F6B.toInt(),
        0xFF00AD43.toInt(),
        0xFF00A550.toInt(),
        0xFF66B032.toInt(),
        0xFF00FF00.toInt(),
        0xFFA7F432.toInt(),
        0xFF6EAEA1.toInt(),
        0xFF1164B4.toInt(),
        0xFF2887C8.toInt(),
        0xFF009966.toInt(),
        0xFFADFF2F.toInt(),
        0xFFF0E891.toInt(),
        0xFFA99A86.toInt(),
        0xFF2A3439.toInt(),
        0xFF446CCF.toInt(),
        0xFF5218FA.toInt(),
        0xFFE9D66B.toInt(),
        0xFF3FFF00.toInt(),
        0xFFDA9100.toInt(),
        0xFFFF7A00.toInt(),
        0xFFDF73FF.toInt(),
        0xFFAA98A9.toInt(),
        0xFFF400A1.toInt(),
        0xFFF0FFF0.toInt(),
        0xFF006DB0.toInt(),
        0xFF49796B.toInt(),
        0xFFFF1DCE.toInt(),
        0xFFFF69B4.toInt(),
        0xFF355E3B.toInt(),
        0xFF71A6D2.toInt(),
        0xFFFCF75E.toInt(),
        0xFF319177.toInt(),
        0xFFED2939.toInt(),
        0xFFB2EC5D.toInt(),
        0xFF4C516D.toInt(),
        0xFF138808.toInt(),
        0xFFCD5C5C.toInt(),
        0xFFE3A857.toInt(),
        0xFF4B0082.toInt(),
        0xFF00416A.toInt(),
        0xFF091F92.toInt(),
        0xFF002FA7.toInt(),
        0xFFFF4F00.toInt(),
        0xFFBA160C.toInt(),
        0xFFC0362C.toInt(),
        0xFF5A4FCF.toInt(),
        0xFFB3446C.toInt(),
        0xFFF4F0EC.toInt(),
        0xFF009000.toInt(),
        0xFFB2FFFF.toInt(),
        0xFFFFFFF0.toInt(),
        0xFF00A86B.toInt(),
        0xFFF8DE7E.toInt(),
        0xFFA50B5E.toInt(),
        0xFF343434.toInt(),
        0xFFF4CA16.toInt(),
        0xFFBDDA57.toInt(),
        0xFF29AB87.toInt(),
        0xFF4CBB17.toInt(),
        0xFF3AB09E.toInt(),
        0xFFE8F48C.toInt(),
        0xFFC3B091.toInt(),
        0xFFF0E68C.toInt(),
        0xFF882D17.toInt(),
        0xFFE79FC4.toInt(),
        0xFF6B4423.toInt(),
        0xFF354230.toInt(),
        0xFF512888.toInt(),
        0xFFD6CADD.toInt(),
        0xFF26619C.toInt(),
        0xFFFFFF66.toInt(),
        0xFFA9BA9D.toInt(),
        0xFFCF1020.toInt(),
        0xFFB57EDC.toInt(),
        0xFFE6E6FA.toInt(),
        0xFFCCCCFF.toInt(),
        0xFFFFF0F5.toInt(),
        0xFFC4C3D0.toInt(),
        0xFFEE82EE.toInt(),
        0xFF7CFC00.toInt(),
        0xFFFFF700.toInt(),
        0xFFFFFACD.toInt(),
        0xFFCCA01D.toInt(),
        0xFFFDFF00.toInt(),
        0xFFF6EABE.toInt(),
        0xFFFFF44F.toInt(),
        0xFFFFFF9F.toInt(),
        0xFF545AA7.toInt(),
        0xFFFDD5B1.toInt(),
        0xFFADD8E6.toInt(),
        0xFFB5651D.toInt(),
        0xFF551F2F.toInt(),
        0xFF88ACE0.toInt(),
        0xFFF08080.toInt(),
        0xFF93CCEA.toInt(),
        0xFFF56991.toInt(),
        0xFFE0FFFF.toInt(),
        0xFFFF5CCD.toInt(),
        0xFFC8AD7F.toInt(),
        0xFFF984EF.toInt(),
        0xFFB29700.toInt(),
        0xFFFAFAD2.toInt(),
        0xFFD3D3D3.toInt(),
        0xFFCC99CC.toInt(),
        0xFF90EE90.toInt(),
        0xFFFFB3DE.toInt(),
        0xFFF0E68C.toInt(),
        0xFFFF80FF.toInt(),
        0xFFD39BCB.toInt(),
        0xFFADDFAD.toInt(),
        0xFFFED8B1.toInt(),
        0xFFE6A8D7.toInt(),
        0xFFB19CD9.toInt(),
        0xFFC5CBE1.toInt(),
        0xFFFFB6C1.toInt(),
        0xFFFFCCCB.toInt(),
        0xFFE97451.toInt(),
        0xFFFFA07A.toInt(),
        0xFFFF9999.toInt(),
        0xFF20B2AA.toInt(),
        0xFFD8D8D8.toInt(),
        0xFF87CEFA.toInt(),
        0xFF778899.toInt(),
        0xFFB0C4DE.toInt(),
        0xFFB38B6D.toInt(),
        0xFFFFFFE0.toInt(),
        0xFFC8A2C8.toInt(),
        0xFFAE98AA.toInt(),
        0xFFBFFF00.toInt(),
        0xFF00FF00.toInt(),
        0xFF32CD32.toInt(),
        0xFF195905.toInt(),
        0xFFFAF0E6.toInt(),
        0xFFC19A6B.toInt(),
        0xFFDE6FA1.toInt(),
        0xFF6CA0DC.toInt(),
        0xFFF8B9D4.toInt(),
        0xFF674C47.toInt(),
        0xFFB86D29.toInt(),
        0xFF6C2E1F.toInt(),
        0xFF987456.toInt(),
        0xFF6699CC.toInt(),
        0xFFFEFDFA.toInt(),
        0xFFFFBD88.toInt(),
        0xFFCC3336.toInt(),
        0xFFFF00FF.toInt(),
        0xFFFF55A3.toInt(),
        0xFFCA1F7B.toInt(),
        0xFFD0417E.toInt(),
        0xFFFF0090.toInt(),
        0xFF9F4576.toInt(),
        0xFFAAF0D1.toInt(),
        0xFFFF4466.toInt(),
        0xFFF8F4FF.toInt(),
        0xFFC04000.toInt(),
        0xFFFBEC5D.toInt(),
        0xFFF2C649.toInt(),
        0xFF6050DC.toInt(),
        0xFF0BDA51.toInt(),
        0xFF979AAA.toInt(),
        0xFFF37A48.toInt(),
        0xFFFDBE02.toInt(),
        0xFF96FF00.toInt(),
        0xFFFF8243.toInt(),
        0xFFE7C9A9.toInt(),
        0xFF74C365.toInt(),
        0xFFBB9351.toInt(),
        0xFF880085.toInt(),
        0xFFF2D930.toInt(),
        0xFFEAA221.toInt(),
        0xFFC32148.toInt(),
        0xFF800000.toInt(),
        0xFFB03060.toInt(),
        0xFFE0B0FF.toInt(),
        0xFF915F6D.toInt(),
        0xFFEF98AA.toInt(),
        0xFF47ABCC.toInt(),
        0xFF30BFBF.toInt(),
        0xFFACACE6.toInt(),
        0xFF5E8C31.toInt(),
        0xFFD9E650.toInt(),
        0xFFFF5B00.toInt(),
        0xFF733380.toInt(),
        0xFFD92121.toInt(),
        0xFFA63A79.toInt(),
        0xFFFAFA37.toInt(),
        0xFFF2BA49.toInt(),
        0xFF4C9141.toInt(),
        0xFF73C2FB.toInt(),
        0xFF66DDAA.toInt(),
        0xFF0000CD.toInt(),
        0xFFE2062C.toInt(),
        0xFFAF4035.toInt(),
        0xFFF3E5AB.toInt(),
        0xFF035096.toInt(),
        0xFF1C352D.toInt(),
        0xFFDDA0DD.toInt(),
        0xFFBA55D3.toInt(),
        0xFF0067A5.toInt(),
        0xFF9370DB.toInt(),
        0xFFBB3385.toInt(),
        0xFFAA4069.toInt(),
        0xFF3CB371.toInt(),
        0xFF80DAEB.toInt(),
        0xFF7B68EE.toInt(),
        0xFFC9DC87.toInt(),
        0xFF00FA9A.toInt(),
        0xFF674C47.toInt(),
        0xFF48D1CC.toInt(),
        0xFF79443B.toInt(),
        0xFFD9603B.toInt(),
        0xFFC71585.toInt(),
        0xFFFDBCB4.toInt(),
        0xFFF8B878.toInt(),
        0xFFF8DE7E.toInt(),
        0xFFFEBAAD.toInt(),
        0xFFD3AF37.toInt(),
        0xFF0A7E8C.toInt(),
        0xFF9C7C38.toInt(),
        0xFFE4007C.toInt(),
        0xFF7ED4E6.toInt(),
        0xFF8DD9CC.toInt(),
        0xFF8B72BE.toInt(),
        0xFF4D8C57.toInt(),
        0xFFACBF60.toInt(),
        0xFF8B8680.toInt(),
        0xFFD982B5.toInt(),
        0xFFE58E73.toInt(),
        0xFFA55353.toInt(),
        0xFFFFEB00.toInt(),
        0xFFECB176.toInt(),
        0xFF702670.toInt(),
        0xFF191970.toInt(),
        0xFF004953.toInt(),
        0xFFFFC40C.toInt(),
        0xFFFFDAE9.toInt(),
        0xFFE3F988.toInt(),
        0xFF36747D.toInt(),
        0xFFF5E050.toInt(),
        0xFF3EB489.toInt(),
        0xFFF5FFFA.toInt(),
        0xFF98FF98.toInt(),
        0xFFBBB477.toInt(),
        0xFFFFE4E1.toInt(),
        0xFF967117.toInt(),
        0xFF8DA399.toInt(),
        0xFF8A9A5B.toInt(),
        0xFF30BA8F.toInt(),
        0xFF997A8D.toInt(),
        0xFF18453B.toInt(),
        0xFFC54B8C.toInt(),
        0xFFC8509B.toInt(),
        0xFFFFDB58.toInt(),
        0xFF317873.toInt(),
        0xFFD65282.toInt(),
        0xFFAD4379.toInt(),
        0xFFFADA5E.toInt(),
        0xFFFFDEAD.toInt(),
        0xFF000080.toInt(),
        0xFF1974D2.toInt(),
        0xFF4666FF.toInt(),
        0xFF39FF14.toInt(),
        0xFFD7837F.toInt(),
        0xFF727472.toInt(),
        0xFFE4000F.toInt(),
        0xFFA4DDED.toInt(),
        0xFFE9FFDB.toInt(),
        0xFF4F42B5.toInt(),
        0xFF48BF91.toInt(),
        0xFFCC7722.toInt(),
        0xFF008000.toInt(),
        0xFF43302E.toInt(),
        0xFFCFB53B.toInt(),
        0xFF563C5C.toInt(),
        0xFFFDF5E6.toInt(),
        0xFF796878.toInt(),
        0xFF673147.toInt(),
        0xFFC08081.toInt(),
        0xFF848482.toInt(),
        0xFF808000.toInt(),
        0xFF3C341F.toInt(),
        0xFF6B8E23.toInt(),
        0xFFB5B35C.toInt(),
        0xFF9AB973.toInt(),
        0xFF353839.toInt(),
        0xFFA8C3BC.toInt(),
        0xFFB784A7.toInt(),
        0xFFFF6600.toInt(),
        0xFFFF7F00.toInt(),
        0xFFFF7538.toInt(),
        0xFFFF5800.toInt(),
        0xFFFB9902.toInt(),
        0xFFFFA500.toInt(),
        0xFFFF9F00.toInt(),
        0xFFFA5B3D.toInt(),
        0xFFFF681F.toInt(),
        0xFFFF5349.toInt(),
        0xFFF5BD1F.toInt(),
        0xFFF8D568.toInt(),
        0xFFDA70D6.toInt(),
        0xFFE29CD2.toInt(),
        0xFFF2BDCD.toInt(),
        0xFF841617.toInt(),
        0xFF414A4C.toInt(),
        0xFF2D383A.toInt(),
        0xFFFF6E4A.toInt(),
        0xFF800020.toInt(),
        0xFF002147.toInt(),
        0xFF1CA9C9.toInt(),
        0xFF006600.toInt(),
        0xFF273BE2.toInt(),
        0xFF682860.toInt(),
        0xFFBCD4E6.toInt(),
        0xFF9BC4E2.toInt(),
        0xFFDA8A67.toInt(),
        0xFFE6BE8A.toInt(),
        0xFFEEE8AA.toInt(),
        0xFFDCD0FF.toInt(),
        0xFFFADADD.toInt(),
        0xFFDDA0DD.toInt(),
        0xFFFAE6FA.toInt(),
        0xFFDB7093.toInt(),
        0xFF96DED1.toInt(),
        0xFFC9C0BB.toInt(),
        0xFFECEBBD.toInt(),
        0xFFBC987E.toInt(),
        0xFF78184A.toInt(),
        0xFF009B7D.toInt(),
        0xFFFFEFD5.toInt(),
        0xFFE63E62.toInt(),
        0xFF50C878.toInt(),
        0xFFDEA5A4.toInt(),
        0xFF800080.toInt(),
        0xFF536878.toInt(),
        0xFFFFE5B4.toInt(),
        0xFFFFDAB9.toInt(),
        0xFFD1E231.toInt(),
        0xFFEAE0C8.toInt(),
        0xFFB768A2.toInt(),
        0xFFCCCCFF.toInt(),
        0xFFC3CDE6.toInt(),
        0xFFE12C2C.toInt(),
        0xFF1C39BB.toInt(),
        0xFF00A693.toInt(),
        0xFF32127A.toInt(),
        0xFFD99058.toInt(),
        0xFFF77FBE.toInt(),
        0xFF701C1C.toInt(),
        0xFFCC3333.toInt(),
        0xFFFE28A2.toInt(),
        0xFFEC5800.toInt(),
        0xFF8BA8B7.toInt(),
        0xFFDF00FF.toInt(),
        0xFF000F89.toInt(),
        0xFF123524.toInt(),
        0xFF2E2787.toInt(),
        0xFFC30B4E.toInt(),
        0xFFFDDDE6.toInt(),
        0xFF01796F.toInt(),
        0xFF2A2F23.toInt(),
        0xFFFFC0CB.toInt(),
        0xFFD74894.toInt(),
        0xFFFC74FD.toInt(),
        0xFFFFDDF4.toInt(),
        0xFFD8B2D1.toInt(),
        0xFFF78FA7.toInt(),
        0xFF93C572.toInt(),
        0xFFE5E4E2.toInt(),
        0xFF8E4585.toInt(),
        0xFFDDA0DD.toInt(),
        0xFF5946B2.toInt(),
        0xFF5DA493.toInt(),
        0xFF86608E.toInt(),
        0xFFBE4F62.toInt(),
        0xFFFF5A36.toInt(),
        0xFFB0E0E6.toInt(),
        0xFFF58025.toInt(),
        0xFF701C1C.toInt(),
        0xFF003153.toInt(),
        0xFFDF00FF.toInt(),
        0xFFCC8899.toInt(),
        0xFF644117.toInt(),
        0xFFFF7518.toInt(),
        0xFF6A0DAD.toInt(),
        0xFF800080.toInt(),
        0xFF9F00C5.toInt(),
        0xFFA020F0.toInt(),
        0xFF9678B6.toInt(),
        0xFF4E5180.toInt(),
        0xFFFE4EDA.toInt(),
        0xFF9C51B6.toInt(),
        0xFF9A4EAE.toInt(),
        0xFF436B95.toInt(),
        0xFFE8CCD7.toInt(),
        0xFFA6A6A6.toInt(),
        0xFF8E3A59.toInt(),
        0xFFFF355E.toInt(),
        0xFF242124.toInt(),
        0xFFFBAB60.toInt(),
        0xFFE30B5D.toInt(),
        0xFF915F6D.toInt(),
        0xFFB3446C.toInt(),
        0xFFD68A59.toInt(),
        0xFF826644.toInt(),
        0xFFFF33CC.toInt(),
        0xFFE3256B.toInt(),
        0xFF8D4E85.toInt(),
        0xFF663399.toInt(),
        0xFFFF0000.toInt(),
        0xFFEE204D.toInt(),
        0xFFF2003C.toInt(),
        0xFFC40233.toInt(),
        0xFFED2939.toInt(),
        0xFFED1C24.toInt(),
        0xFFFE2712.toInt(),
        0xFFFD3A4A.toInt(),
        0xFFFF5349.toInt(),
        0xFFFF4500.toInt(),
        0xFFFF681F.toInt(),
        0xFFE40078.toInt(),
        0xFFC71585.toInt(),
        0xFF922B3E.toInt(),
        0xFFC0448F.toInt(),
        0xFFA45A52.toInt(),
        0xFF000000.toInt(),
        0xFF002387.toInt(),
        0xFF777696.toInt(),
        0xFF004040.toInt(),
        0xFF010B13.toInt(),
        0xFF010203.toInt(),
        0xFFD70040.toInt(),
        0xFFB666D2.toInt(),
        0xFFB03060.toInt(),
        0xFF444C38.toInt(),
        0xFF00CCCC.toInt(),
        0xFF8A7F80.toInt(),
        0xFF838996.toInt(),
        0xFFFF007F.toInt(),
        0xFFF9429E.toInt(),
        0xFF9E5E6F.toInt(),
        0xFF674846.toInt(),
        0xFFE32636.toInt(),
        0xFFFF66CC.toInt(),
        0xFFAA98A9.toInt(),
        0xFFC21E56.toInt(),
        0xFF905D5D.toInt(),
        0xFFAB4E52.toInt(),
        0xFF65000B.toInt(),
        0xFFD40000.toInt(),
        0xFFBC8F8F.toInt(),
        0xFF002366.toInt(),
        0xFF4169E1.toInt(),
        0xFF7851A9.toInt(),
        0xFFFADA5E.toInt(),
        0xFFCE4676.toInt(),
        0xFFD10056.toInt(),
        0xFFE0115F.toInt(),
        0xFF9B111E.toInt(),
        0xFFA81C07.toInt(),
        0xFF80461B.toInt(),
        0xFF679267.toInt(),
        0xFF32174D.toInt(),
        0xFFB7410E.toInt(),
        0xFFDA2C43.toInt(),
        0xFF043927.toInt(),
        0xFF8B4513.toInt(),
        0xFFFF7800.toInt(),
        0xFFFF6700.toInt(),
        0xFFEED202.toInt(),
        0xFFF4C430.toInt(),
        0xFFBCB88A.toInt(),
        0xFFFA8072.toInt(),
        0xFFFF91A4.toInt(),
        0xFFC2B280.toInt(),
        0xFF967117.toInt(),
        0xFFF4A460.toInt(),
        0xFF967117.toInt(),
        0xFF507D2A.toInt(),
        0xFF0F52BA.toInt(),
        0xFF0067A5.toInt(),
        0xFF0067A5.toInt(),
        0xFFCBA135.toInt(),
        0xFFFF2400.toInt(),
        0xFFFF91AF.toInt(),
        0xFFFFD800.toInt(),
        0xFF66FF66.toInt(),
        0xFF2E8B57.toInt(),
        0xFF00FFCD.toInt(),
        0xFF59260B.toInt(),
        0xFFFFF5EE.toInt(),
        0xFFFFBA00.toInt(),
        0xFF704214.toInt(),
        0xFF8A795D.toInt(),
        0xFF778BA5.toInt(),
        0xFF009E60.toInt(),
        0xFF8FD400.toInt(),
        0xFFD98695.toInt(),
        0xFF5FA778.toInt(),
        0xFFFC0FC0.toInt(),
        0xFFFF6FFF.toInt(),
        0xFF882D17.toInt(),
        0xFFC0C0C0.toInt(),
        0xFFC9C0BB.toInt(),
        0xFFAAA9AD.toInt(),
        0xFFACACAC.toInt(),
        0xFFAFB1AE.toInt(),
        0xFF5D89BA.toInt(),
        0xFFC4AEAD.toInt(),
        0xFFBFC1C2.toInt(),
        0xFFCB410B.toInt(),
        0xFFFF3855.toInt(),
        0xFFFFDB00.toInt(),
        0xFF007474.toInt(),
        0xFF87CEEB.toInt(),
        0xFF76D7EA.toInt(),
        0xFFCF71AF.toInt(),
        0xFF6A5ACD.toInt(),
        0xFF708090.toInt(),
        0xFF299617.toInt(),
        0xFF003399.toInt(),
        0xFFC84186.toInt(),
        0xFF100C08.toInt(),
        0xFF933D41.toInt(),
        0xFFFFFAFA.toInt(),
        0xFF893843.toInt(),
        0xFF757575.toInt(),
        0xFF1D2951.toInt(),
        0xFF807532.toInt(),
        0xFF0070B8.toInt(),
        0xFFD10047.toInt(),
        0xFF989898.toInt(),
        0xFF009150.toInt(),
        0xFFE86100.toInt(),
        0xFFF7BFBE.toInt(),
        0xFFE60026.toInt(),
        0xFF00FFFF.toInt(),
        0xFF4C2882.toInt(),
        0xFF007F5C.toInt(),
        0xFFA7FC00.toInt(),
        0xFF87FF2A.toInt(),
        0xFF00FF7F.toInt(),
        0xFFECEBBD.toInt(),
        0xFF23297A.toInt(),
        0xFF007BB8.toInt(),
        0xFF4682B4.toInt(),
        0xFFCC33CC.toInt(),
        0xFF5F8A8B.toInt(),
        0xFFFADA5E.toInt(),
        0xFFE4D96F.toInt(),
        0xFF914E75.toInt(),
        0xFFFFCC33.toInt(),
        0xFFE3AB57.toInt(),
        0xFFFAD6A5.toInt(),
        0xFFCF6BA9.toInt(),
        0xFFA83731.toInt(),
        0xFFD2B48C.toInt(),
        0xFFD99A6C.toInt(),
        0xFFF28500.toInt(),
        0xFFE4717A.toInt(),
        0xFFFB4D46.toInt(),
        0xFF483C32.toInt(),
        0xFF8B8589.toInt(),
        0xFFD0F0C0.toInt(),
        0xFFF88379.toInt(),
        0xFF008080.toInt(),
        0xFF367588.toInt(),
        0xFFCF3476.toInt(),
        0xFFCD5700.toInt(),
        0xFFE2725B.toInt(),
        0xFFD8BFD8.toInt(),
        0xFFDE6FA1.toInt(),
        0xFFFC89AC.toInt(),
        0xFF0ABAB5.toInt(),
        0xFFDBD7D2.toInt(),
        0xFFEEE600.toInt(),
        0xFFFF6347.toInt(),
        0xFF00755E.toInt(),
        0xFF2D68C4.toInt(),
        0xFF3E8EDE.toInt(),
        0xFFDEAA88.toInt(),
        0xFF40E0D0.toInt(),
        0xFF00FFEF.toInt(),
        0xFFA0D6B4.toInt(),
        0xFF8A9A5B.toInt(),
        0xFFFAD6A5.toInt(),
        0xFF6F4E37.toInt(),
        0xFF7C4848.toInt(),
        0xFFA67B5B.toInt(),
        0xFFC09999.toInt(),
        0xFF8A496B.toInt(),
        0xFF66023C.toInt(),
        0xFF0033AA.toInt(),
        0xFFD9004C.toInt(),
        0xFFFF6FFF.toInt(),
        0xFFFC6C85.toInt(),
        0xFF3F00FF.toInt(),
        0xFF4166F5.toInt(),
        0xFF635147.toInt(),
        0xFFFFDDCA.toInt(),
        0xFF5B92E5.toInt(),
        0xFFFFFF66.toInt(),
        0xFF014421.toInt(),
        0xFF7B1113.toInt(),
        0xFFAE2029.toInt(),
        0xFF004F98.toInt(),
        0xFF664228.toInt(),
        0xFFF3E5AB.toInt(),
        0xFFF38FA9.toInt(),
        0xFFC5B358.toInt(),
        0xFFC80815.toInt(),
        0xFF43B3AE.toInt(),
        0xFFE34234.toInt(),
        0xFFA020F0.toInt(),
        0xFF8F00FF.toInt(),
        0xFF7F00FF.toInt(),
        0xFF963D7F.toInt(),
        0xFF8601AF.toInt(),
        0xFFEE82EE.toInt(),
        0xFF324AB2.toInt(),
        0xFF766EC8.toInt(),
        0xFFF75394.toInt(),
        0xFF40826D.toInt(),
        0xFF009698.toInt(),
        0xFF9F1D35.toInt(),
        0xFF00CCFF.toInt(),
        0xFFFFA089.toInt(),
        0xFF9F00FF.toInt(),
        0xFFCEFF00.toInt(),
        0xFF004242.toInt(),
        0xFFF5DEB3.toInt(),
        0xFFFFFFFF.toInt(),
        0xFFA2ADD0.toInt(),
        0xFFD470A2.toInt(),
        0xFFFF43A4.toInt(),
        0xFFFC6C85.toInt(),
        0xFFA75502.toInt(),
        0xFF722F37.toInt(),
        0xFF673147.toInt(),
        0xFFFF007C.toInt(),
        0xFF56887D.toInt(),
        0xFFC9A0DC.toInt(),
        0xFFC19A6B.toInt(),
        0xFF0F4D92.toInt(),
        0xFFFFFF00.toInt(),
        0xFFFCE883.toInt(),
        0xFFEFCC00.toInt(),
        0xFFFFD300.toInt(),
        0xFFFEDF00.toInt(),
        0xFFFFEF00.toInt(),
        0xFFFEFE33.toInt(),
        0xFFFFAE42.toInt(),
        0xFFFF9505.toInt(),
        0xFFFFF700.toInt(),
        0xFF9ACD32.toInt(),
        0xFF30B21A.toInt(),
        0xFFC5E384.toInt(),
        0xFF2E5090.toInt(),
        0xFF0014A8.toInt(),
        0xFF39A78E.toInt()
    )

    /**
     * search("blu") -> ["Blue", "Blue Dark", ...]
     * Strategy:
     *  1) fast prefix matches (binary search on sorted names)
     *  2) if not enough, fill with substring contains matches (bounded)
     */
    fun search(query: String, limit: Int = 20): List<Result> {
        val q = norm(query)
        if (q.isBlank()) return emptyList()
        val out = ArrayList<Result>(limit)
        val used = HashSet<Int>()

        // ---- 1) prefix matches ----
        val start = lowerBound(NAMES_NORM, q)
        var i = start
        while (i < NAMES_NORM.size && out.size < limit) {
            val n = NAMES_NORM[i]
            if (!n.startsWith(q)) break
            if (used.add(i)) out.add(Result(NAMES[i], ARGB[i]))
            i++
        }

        // ---- 2) substring fill (bounded scan) ----
        if (out.size < limit) {
            var scanned = 0
            var j = 0
            while (j < NAMES_NORM.size && out.size < limit && scanned < 4000) {
                val n = NAMES_NORM[j]
                if (n.contains(q) && used.add(j)) out.add(Result(NAMES[j], ARGB[j]))
                j++; scanned++
            }
        }

        return out
    }

    // standard lower_bound for Array<String>
    private fun lowerBound(a: Array<String>, key: String): Int {
        var lo = 0
        var hi = a.size
        while (lo < hi) {
            val mid = (lo + hi) ushr 1
            if (a[mid] < key) lo = mid + 1 else hi = mid
        }
        return lo
    }

    fun allColors(): List<PickedColor> {
        // Adjust to your actual internal storage.
        // If you have arrays like `names` + `argbs`, do this:
        return NAMES.indices.map { i ->
            PickedColor(argb = ARGB[i], name = NAMES[i])
        }
    }
}
